use db2024;

insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'sea salt');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'garlic cloves');
insert into image (image, description) values ('eggs.jpg', 'sea salt');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'garlic cloves');
insert into image (image, description) values ('salt.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('eggs.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'sea salt');
insert into image (image, description) values ('butter.jpg', 'organic basil');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('butter.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'fresh tomatoes');
insert into image (image, description) values ('sugar.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('flour.jpg', 'organic basil');
insert into image (image, description) values ('salt.jpg', 'extra virgin olive oil');
insert into image (image, description) values ('salt.jpg', 'organic basil');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'fresh tomatoes');
insert into image (image, description) values ('butter.jpg', 'garlic cloves');
insert into image (image, description) values ('flour.jpg', 'fresh tomatoes');
insert into image (image, description) values ('eggs.jpg', 'organic basil');
insert into image (image, description) values (LOAD_FILE('C:\Users\evief\OneDrive\Εικόνες\08 gettyimages-974862038_resized.jpg'), 'fresh tomatoes');



select * FROM image where 1000<=image_id;