INSERT INTO Equipment (name, description, image_id) VALUES ('apron', 'A protective garment worn over clothes, typically tied around the waist, used to keep clothes clean while cooking or working in the kitchen.', 478);
INSERT INTO Equipment (name, description, image_id) VALUES ('blender', 'A kitchen appliance with rotating blades used to blend, puree, or mix ingredients into smoothies, soups, sauces, and other dishes.', 479);
INSERT INTO Equipment (name, description, image_id) VALUES ('bottle', 'A container typically made of glass or plastic, used for storing liquids such as water, oil, vinegar, or sauces in the kitchen.', 480);
INSERT INTO Equipment (name, description, image_id) VALUES ('bottle opener', 'A tool designed to remove metal caps or corks from bottles, commonly used for opening beer or wine bottles.', 481);
INSERT INTO Equipment (name, description, image_id) VALUES ('bowl', 'A round, deep dish used for holding or serving food, typically made of ceramic, glass, or metal.', 482);
INSERT INTO Equipment (name, description, image_id) VALUES ('butter knife', 'A small knife with a blunt edge, used for spreading butter or other spreads onto bread or toast.', 483);
INSERT INTO Equipment (name, description, image_id) VALUES ('cake slicer', 'A utensil with a long, thin blade used for slicing cakes into even portions, ensuring neat and uniform servings.', 484);
INSERT INTO Equipment (name, description, image_id) VALUES ('chopsticks', 'Two slender sticks made of wood or metal, used in pairs for picking up and eating food in East Asian cuisines.', 485);
INSERT INTO Equipment (name, description, image_id) VALUES ('colander', 'A perforated bowl-shaped kitchen utensil used for draining water from cooked pasta, vegetables, or other foods.', 486);
INSERT INTO Equipment (name, description, image_id) VALUES ('cleaver', 'A large, heavy knife with a broad blade, used for chopping through bones or large cuts of meat.', 487);
INSERT INTO Equipment (name, description, image_id) VALUES ('microwave', 'A kitchen appliance that uses electromagnetic radiation to heat and cook food quickly, commonly used for reheating leftovers or defrosting frozen food.', 488);
INSERT INTO Equipment (name, description, image_id) VALUES ('corkscrew', 'A tool with a spiral metal shaft for drawing corks from wine bottles, often featuring a handle for twisting.', 489);
INSERT INTO Equipment (name, description, image_id) VALUES ('cup', 'A small, cylindrical container used for drinking, typically made of ceramic, glass, or plastic.', 490);
INSERT INTO Equipment (name, description, image_id) VALUES ('cutlery', 'A collective term for knives, forks, spoons, and other utensils used for eating or serving food.', 491);
INSERT INTO Equipment (name, description, image_id) VALUES ('cutting board', 'A flat board, typically made of wood or plastic, used as a surface for cutting or chopping ingredients in the kitchen.', 492);
INSERT INTO Equipment (name, description, image_id) VALUES ('funnel', 'A conical kitchen tool with a narrow tube at the end, used for pouring liquids or powders into containers without spilling.', 493);
INSERT INTO Equipment (name, description, image_id) VALUES ('dish rack', 'A rack or tray used for holding washed dishes to air dry after washing, typically placed next to the sink in the kitchen.', 494);
INSERT INTO Equipment (name, description, image_id) VALUES ('egg slicer', 'A kitchen utensil with thin wires or blades, used for slicing hard-boiled eggs into even, uniform slices.', 495);
INSERT INTO Equipment (name, description, image_id) VALUES ('deep fryer', 'A kitchen appliance used for deep-frying food by submerging it in hot oil, commonly used for frying foods like French fries, chicken, or fish.', 496);
INSERT INTO Equipment (name, description, image_id) VALUES ('garlic crusher', 'A handheld tool used for crushing garlic cloves by applying pressure, typically resulting in minced or crushed garlic.', 497);
INSERT INTO Equipment (name, description, image_id) VALUES ('kitchen paper', 'A roll of absorbent paper used for cleaning up spills, wiping surfaces, or wrapping food in the kitchen.', 498);
INSERT INTO Equipment (name, description, image_id) VALUES ('gas stove', 'A cooking appliance that uses natural gas or propane as a fuel source to produce a flame for cooking food in pots and pans.', 499);
INSERT INTO Equipment (name, description, image_id) VALUES ('grater', 'A kitchen utensil with a rough surface, used for shredding or grating cheese, vegetables, or other food items into fine pieces.', 500);
INSERT INTO Equipment (name, description, image_id) VALUES ('hot pot', 'A tabletop cooking vessel with a built-in heating element, used for simmering broth and cooking a variety of ingredients at the dining table.', 501);
INSERT INTO Equipment (name, description, image_id) VALUES ('jar', 'A glass or plastic container with a lid, used for storing preserves, jams, sauces, or other food items in the kitchen.', 502);
INSERT INTO Equipment (name, description, image_id) VALUES ('fork', 'A utensil with prongs or tines at one end and a handle at the other, used for picking up and eating food.', 503);
INSERT INTO Equipment (name, description, image_id) VALUES ('knife', 'A sharp-edged cutting tool with a handle, used for slicing, chopping, or carving food in the kitchen.', 504);
INSERT INTO Equipment (name, description, image_id) VALUES ('juicer', 'A kitchen appliance used for extracting juice from fruits or vegetables by pressing or squeezing them.', 505);
INSERT INTO Equipment (name, description, image_id) VALUES ('kitchen towel', 'A cloth or paper towel used for drying hands, wiping surfaces, or handling hot cookware in the kitchen.', 506);
INSERT INTO Equipment (name, description, image_id) VALUES ('kitchen scissors', 'A pair of scissors with sturdy blades, used for cutting food items like herbs, poultry, or packaging materials in the kitchen.', 507);
INSERT INTO Equipment (name, description, image_id) VALUES ('jug', 'A large, narrow-necked container with a handle and a spout, used for pouring liquids like water, juice, or milk.', 508);
INSERT INTO Equipment (name, description, image_id) VALUES ('kettle', 'A metal or ceramic vessel with a handle and spout, used for boiling water or brewing tea or coffee on the stovetop.', 509);
INSERT INTO Equipment (name, description, image_id) VALUES ('oven gloves', 'Thick, heat-resistant gloves worn to protect hands and arms when handling hot cookware or baking in the oven.', 510);
INSERT INTO Equipment (name, description, image_id) VALUES ('knife set', 'A collection of knives of various types and sizes, typically stored together in a block or on a magnetic strip in the kitchen.', 511);
INSERT INTO Equipment (name, description, image_id) VALUES ('ladle', 'A long-handled spoon with a deep bowl, used for serving soups, stews, sauces, or other liquid dishes.', 512);
INSERT INTO Equipment (name, description, image_id) VALUES ('lemon squeezer', 'A handheld tool used for extracting juice from lemons or other citrus fruits by pressing or squeezing them.', 513);
INSERT INTO Equipment (name, description, image_id) VALUES ('matchbox', 'A small cardboard box containing matches, used for lighting gas stoves, candles, or other combustible materials.', 514);
INSERT INTO Equipment (name, description, image_id) VALUES ('measuring cup', 'A graduated container used for accurately measuring liquid or dry ingredients in recipes.', 515);
INSERT INTO Equipment (name, description, image_id) VALUES ('mixer', 'A kitchen appliance with rotating beaters or blades, used for mixing, beating, or whipping ingredients together in baking or cooking.', 516);
INSERT INTO Equipment (name, description, image_id) VALUES ('sieve', 'A utensil consisting of a meshed or perforated metal or nylon screen, used for straining liquids or sifting dry ingredients in cooking or baking.', 517);
INSERT INTO Equipment (name, description, image_id) VALUES ('spatula', 'A flat, flexible utensil with a broad, flat blade, used for lifting, flipping, or spreading food items like pancakes, burgers, or frosting.', 518);
INSERT INTO Equipment (name, description, image_id) VALUES ('napkin', 'A square or rectangular piece of cloth or paper used for wiping the mouth, hands, or utensils during meals.', 519);
INSERT INTO Equipment (name, description, image_id) VALUES ('wok', 'A round-bottomed cooking pan with sloping sides and a long handle, used for stir-frying, deep-frying, steaming, or braising in Chinese cuisine.', 520);
INSERT INTO Equipment (name, description, image_id) VALUES ('whisk', 'A kitchen utensil consisting of a handle with thin wire loops, used for beating, whipping, or mixing ingredients together.', 521);
INSERT INTO Equipment (name, description, image_id) VALUES ('perforated spoon', 'A spoon with holes or slots in the bowl, used for draining or skimming liquids or removing solid ingredients from liquid.', 522);
INSERT INTO Equipment (name, description, image_id) VALUES ('peeler', 'A handheld tool with a sharp blade, used for removing the outer skin or peel from fruits and vegetables.', 523);
INSERT INTO Equipment (name, description, image_id) VALUES ('peppermill', 'A grinder or mill used for grinding peppercorns to produce freshly ground pepper for seasoning food.', 524);
INSERT INTO Equipment (name, description, image_id) VALUES ('rolling pin', 'A cylindrical tool used in baking for flattening and shaping dough into thin sheets or rounds.', 525);
INSERT INTO Equipment (name, description, image_id) VALUES ('pizza cutter', 'A sharp, wheeled tool used for cutting pizzas into slices quickly and cleanly.', 526);
INSERT INTO Equipment (name, description, image_id) VALUES ('potato masher', 'A utensil with a grid of wires or blades, used for mashing cooked potatoes or other vegetables into a smooth or chunky consistency.', 527);
