use db2024;
BEGIN;

#insert 20 National Cuisines
INSERT INTO National_Cuisine (country_name) VALUES ('Greece');
INSERT INTO National_Cuisine (country_name) VALUES ('Azerbaijan');
INSERT INTO National_Cuisine (country_name) VALUES ('Australia');
INSERT INTO National_Cuisine (country_name) VALUES ('Vietnam');
INSERT INTO National_Cuisine (country_name) VALUES ('France');
INSERT INTO National_Cuisine (country_name) VALUES ('Georgia');
INSERT INTO National_Cuisine (country_name) VALUES ('Esthonia');
INSERT INTO National_Cuisine (country_name) VALUES ('Japan');
INSERT INTO National_Cuisine (country_name) VALUES ('India');
INSERT INTO National_Cuisine (country_name) VALUES ('Italy');
INSERT INTO National_Cuisine (country_name) VALUES ('China');
INSERT INTO National_Cuisine (country_name) VALUES ('Cyprus');
INSERT INTO National_Cuisine (country_name) VALUES ('Belarus');
INSERT INTO National_Cuisine (country_name) VALUES ('Ukraine');
INSERT INTO National_Cuisine (country_name) VALUES ('Poland');
INSERT INTO National_Cuisine (country_name) VALUES ('Russia');
INSERT INTO National_Cuisine (country_name) VALUES ('Serbia');
INSERT INTO National_Cuisine (country_name) VALUES ('Tayland');
INSERT INTO National_Cuisine (country_name) VALUES ('Turkey');
INSERT INTO National_Cuisine (country_name) VALUES ('Moldova');


#insert 12 food groups
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Coffee','In this category there is coffee, tea and all other derived products','based on coffee', 1);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Spices','In this category you can find spices and essential oils','based on spices', 2);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Preserved foods','In this category you can find preserved foods of every kind','based on preserved foods', 3);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Sweeteners','In this category you can find every type of sweetener','based on sweeteners', 4);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Fats and oils','In this category you can find every type of fats and oils','based on fats and oils', 5);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Milk and eggs','In this category you can find food related to milk, eggs and their products','based on milk and eggs', 6);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Meat','In this category you can find all types of meat and its products','based on meat', 7);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Fish','In this category you can find all types of fish and their products','based on fish', 8);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Cereal','In this category you can find all types of cereals and their products','based on cereal', 9);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Plant origin','In this category you can find various foods of plant origin','based on plants', 10);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Products with sweeteners','In this category you can find all types of products with sweeteners','based on products with sweeteners', 11);
INSERT INTO Food_Group (name, description, characterization_for_recipe, image_id) VALUES ('Drinks','In this category you can find various drinks','based on drinks', 12);

#insert 6 Meal Types
INSERT INTO Meal_Type (meal_type) VALUES ('Breakfast');
INSERT INTO Meal_Type (meal_type) VALUES ('Tea');
INSERT INTO Meal_Type (meal_type) VALUES ('Snack');
INSERT INTO Meal_Type (meal_type) VALUES ('Brunch');
INSERT INTO Meal_Type (meal_type) VALUES ('Supper');
INSERT INTO Meal_Type (meal_type) VALUES ('Dinner');

#insert 200 Ingredients
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Papaw', 11, 169, 128);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oats', 5, 19, 129);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cinnamon', 12, 195, 130);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bamboo Shoots', 1, 134, 131);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jerusalem Artichoke', 8, 127, 132);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nutritional Yeast', 11, 115, 133);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corn Oil', 2, 197, 134);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('SoyFlour', 3, 92, 135);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Beef Stock', 7, 193, 136);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Hokkien Noodles', 9, 52, 137);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Persimmon', 9, 39, 138);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Lettuce', 5, 76, 139);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cantaloupe', 6, 188, 140);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sun dried tomatoes', 11, 77, 141);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple juice', 5, 143, 142);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Butternut lettuce', 6, 90, 143);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Koshihikari rice', 5, 169, 144);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Dates', 12, 187, 145);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Aubergine', 5, 195, 146);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mandarins', 1, 151, 147);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Flat Mushrooms', 7, 193, 148);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Avocado Oil', 10, 174, 149);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Yoghurt', 1, 176, 150);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nectarines', 3, 122, 151);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kidneys', 1, 167, 152);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sausages', 5, 171, 153);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mung Beans', 8, 81, 154);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nutritional Yeast', 5, 90, 155);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Vermicelli Noodles', 11, 145, 156);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Crabs', 11, 155, 157);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sesame seed', 10, 11, 158);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Hummus', 12, 87, 159);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Semolina', 9, 112, 160);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nutritional Yeast', 10, 148, 161);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sesame Oil', 11, 20, 162);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oranges', 2, 173, 163);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Star Fruit', 2, 51, 164);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Vanilla Beans', 8, 140, 165);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pear', 5, 184, 166);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cauliflower', 8, 117, 167);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sugar', 5, 63, 168);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bok Choy', 11, 57, 169);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Salmon', 2, 28, 170);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Farmed Prawns', 11, 86, 171);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cake', 3, 73, 172);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coconut', 8, 183, 173);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Extra Virgin Olive Oil', 5, 90, 174);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jewfish', 5, 20, 175);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Monkfish', 4, 122, 176);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('SwedeSweet Chilli Sauce', 8, 196, 177);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pomegranate', 10, 23, 178);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Carrot', 6, 134, 179);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Macadamia oil', 1, 61, 180);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Butter Beans', 6, 189, 181);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Porcini mushrooms', 7, 190, 182);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Green beans', 12, 150, 183);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Honey', 6, 25, 184);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cream Cheese', 10, 121, 185);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sunflower Oil', 12, 52, 186);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Garam Masala', 2, 192, 187);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mung Beans', 3, 56, 188);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mangosteens', 1, 39, 189);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Leeks', 8, 129, 190);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jewfish', 4, 173, 191);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Scallops', 6, 5, 192);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Avocado', 10, 14, 193);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple juice', 9, 76, 194);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bran', 9, 107, 195);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Star Fruit', 7, 96, 196);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Saffron', 6, 32, 197);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oregano', 12, 138, 198);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cornichons', 11, 27, 199);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Dashi', 3, 189, 200);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kumera', 6, 173, 201);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Peppercorns', 3, 62, 202);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jelly', 8, 61, 203);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kiwi Fruit', 3, 104, 204);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Tom Yum', 2, 181, 205);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Passionfruit', 5, 34, 206);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jelly', 5, 179, 207);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Swiss Chard', 2, 140, 208);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Vermicelli Noodles', 12, 10, 209);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jarrahdale pumpkin', 1, 179, 210);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Ajowan Seed', 8, 18, 211);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Common Cultivated Mushrooms', 9, 168, 212);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cherries', 12, 26, 213);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Black Eyed Beans', 5, 118, 214);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cream', 7, 144, 215);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nashi Pear', 5, 58, 216);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Limes', 6, 49, 217);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Octopus', 7, 190, 218);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Red Pepper', 6, 190, 219);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cauliflower', 8, 143, 220);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kumera', 8, 73, 221);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Lettuce', 5, 74, 222);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('FreshChillies', 7, 35, 223);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mustard Seed', 5, 198, 224);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Tea Oil', 10, 150, 225);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cashews', 8, 38, 226);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oysters', 4, 90, 227);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Garlic', 12, 61, 228);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kidneys', 1, 158, 229);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bran', 1, 73, 230);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Celery', 2, 46, 231);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bamboo Shoots', 10, 183, 232);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('WhiteFlour', 3, 105, 233);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('UnbleachedFlour', 4, 194, 234);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Dandelion', 8, 132, 235);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Peppermint', 8, 135, 236);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mullet', 11, 194, 237);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Saffron', 12, 175, 238);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Extra Virgin Olive Oil', 3, 155, 239);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Blackberries', 11, 67, 240);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cornmeal', 6, 118, 241);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mint', 3, 51, 242);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Edamame', 9, 195, 243);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Capsicum', 6, 182, 244);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Common Cultivated Mushrooms', 10, 193, 245);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Parsley', 1, 25, 246);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pork', 1, 51, 247);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Ajowan Seed', 6, 181, 248);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cheddar', 8, 166, 249);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Chilli Pepper', 11, 128, 250);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Lotus Root', 5, 42, 251);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Potatoes', 12, 160, 252);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pecorino', 8, 106, 253);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cornmeal', 10, 77, 254);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sunflower Oil', 1, 1, 255);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('English Spinach', 3, 29, 256);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sea Salt', 5, 58, 257);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Brown Flour', 8, 140, 258);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pistachio Nut', 4, 35, 259);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Wakame', 10, 54, 260);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Marigold', 9, 173, 261);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oatmeal', 3, 27, 262);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Baking Soda', 7, 14, 263);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('SpeltBread', 5, 81, 264);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Tarragon', 6, 130, 265);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Yogurt', 10, 32, 266);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Ricotta', 12, 75, 267);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Malt vinegar', 11, 152, 268);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Flounder', 4, 169, 269);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Smoked Trout', 10, 79, 270);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Celery Seed', 10, 78, 271);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Squid', 8, 182, 272);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nasturtium', 12, 114, 273);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Spring Onions', 5, 8, 274);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mackerel', 5, 190, 275);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coconut Oil', 10, 136, 276);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Spelt', 2, 25, 277);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Buttermilk', 10, 71, 278);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nectarines', 4, 130, 279);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple juice', 10, 4, 280);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apricots', 1, 74, 281);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sake', 5, 41, 282);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Arborio rice', 2, 111, 283);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sesame Oil', 7, 175, 284);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Buttermilk', 3, 94, 285);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sun dried tomatoes', 11, 191, 286);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sage', 8, 139, 287);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Tom Yum', 12, 25, 288);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Eggplant', 10, 72, 289);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Broccolini', 6, 41, 290);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corn Syrup', 11, 89, 291);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Broccolini', 12, 77, 292);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Szechuan Pepperberry', 7, 190, 293);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Camembert', 6, 180, 294);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coriander Leaves', 1, 57, 295);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Amaranth', 11, 146, 296);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cake', 8, 200, 297);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Whiting Wild Rice', 8, 164, 298);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cream Cheese', 5, 126, 299);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Leeks', 3, 120, 300);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Shark', 8, 106, 301);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cabbage', 6, 46, 302);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bay Leaves', 5, 94, 303);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Prunes', 2, 23, 304);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sugar', 5, 98, 305);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Greenwheat Freekeh', 8, 81, 306);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coconut water', 2, 46, 307);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple Juice Concentrate', 6, 151, 308);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kenchur', 8, 24, 309);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pumpkin Seed', 11, 116, 310);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Wattleseed', 2, 68, 311);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sausages', 7, 46, 312);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Chinese Five Spice', 8, 24, 313);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('FreshChillies', 11, 165, 314);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Butternut pumpkin', 4, 40, 315);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corn Oil', 10, 134, 316);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Papaw', 12, 182, 317);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('WhiteBread', 10, 102, 318);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('FlourRice', 1, 91, 319);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Milk', 9, 31, 320);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Buttermilk', 12, 34, 321);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jarrahdale pumpkin', 10, 58, 322);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Camellia Tea Oil', 2, 102, 323);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Eggs', 10, 136, 324);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Wholemeal', 3, 183, 325);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Lychees', 5, 112, 326);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Porcini mushrooms', 6, 69, 327);


