INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Feta', 8, 103, 128);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('WhiteBread', 2, 185, 129);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pistachio Nut', 10, 149, 130);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mastic', 7, 39, 131);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Stevia', 10, 63, 132);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('WhiteFlour', 7, 184, 133);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Dark Chocolate', 7, 22, 134);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Borlotti Beans', 6, 23, 135);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Flour', 11, 20, 136);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Squid', 4, 111, 137);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Guava', 8, 114, 138);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mackerel', 10, 172, 139);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Calamari', 3, 186, 140);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Barberry', 1, 130, 141);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Parrotfish', 2, 64, 142);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Broccoli', 8, 119, 143);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Licorice', 5, 78, 144);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Barramundi', 7, 88, 145);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Salmon', 10, 111, 146);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cinnamon', 8, 26, 147);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Persimmon', 5, 145, 148);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Haricot Beans', 5, 23, 149);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Capsicum', 5, 144, 150);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Papaya', 12, 138, 151);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Greenwheat Freekeh', 3, 164, 152);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Blackberries', 2, 56, 153);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Peaches', 9, 18, 154);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Strawberries', 8, 185, 155);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Gula MelakaHaloumiHam', 2, 156, 156);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Asian Noodles', 6, 102, 157);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Dates', 2, 143, 158);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Blood oranges', 6, 185, 159);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pear Juice', 10, 117, 160);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Turnips', 6, 176, 161);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Buttermilk', 9, 115, 162);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Juniper Berries', 3, 20, 163);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Scallops', 2, 80, 164);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Porcini mushrooms', 10, 112, 165);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('PepitasPepper', 5, 57, 166);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coconut', 1, 45, 167);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Milk', 2, 75, 168);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oysters', 8, 185, 169);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Achacha', 4, 120, 170);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Blue Swimmer Crab', 6, 129, 171);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Blue Eye Trevalla', 9, 86, 172);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cous Cous', 11, 22, 173);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Asparagus', 7, 128, 174);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corn Oil', 9, 31, 175);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sunflower Seeds', 6, 101, 176);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Broccolini', 5, 31, 177);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Allspice', 6, 139, 178);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coriander Leaves', 4, 29, 179);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sunflower Oil', 6, 109, 180);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pandanus leaves', 6, 54, 181);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cake', 8, 108, 182);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mangosteens', 3, 79, 183);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Tamarillo', 5, 58, 184);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Oyster Mushrooms', 2, 1, 185);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Blueberries', 9, 158, 186);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sesame Seeds', 10, 132, 187);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kudzu', 11, 152, 188);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pumpkin', 10, 165, 189);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Water', 12, 33, 190);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Spring Onions', 5, 157, 191);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Ajowan Seed', 10, 38, 192);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nutmeg', 6, 182, 193);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coconut Oil', 4, 79, 194);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Elderberry', 8, 76, 195);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Grapes', 11, 178, 196);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Camomile', 10, 166, 197);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Balsamic Vinegar', 4, 60, 198);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('SoyFlour', 6, 10, 199);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cardamom', 5, 62, 200);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple Cider Vinegar', 12, 3, 201);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Leeks', 4, 33, 202);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jewfish', 7, 159, 203);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Maple Syrup', 7, 88, 204);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Flounder', 6, 26, 205);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Rosemary', 8, 196, 206);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Green Chicken Curry', 1, 28, 207);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Celery Seed', 8, 72, 208);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('BulghurBurghul', 10, 102, 209);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Curry Powder', 2, 1, 210);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Albacore Tuna', 3, 60, 211);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Chickpea', 10, 4, 212);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Yeast', 8, 178, 213);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple juice', 9, 48, 214);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Rhubarb', 2, 139, 215);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Red Wine Vinegar', 12, 59, 216);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Mountain Bread', 6, 154, 217);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bonza', 1, 102, 218);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Marjoram', 2, 80, 219);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Dill', 1, 83, 220);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Whiting Wild Rice', 8, 180, 221);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Feijoa', 1, 137, 222);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Black Eyed Beans', 10, 92, 223);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Chinese Five Spice', 1, 81, 224);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Green Tea', 6, 5, 225);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Margarine', 12, 46, 226);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Fingerlime', 5, 77, 227);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Potatoes', 6, 200, 228);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Fish Stock', 7, 141, 229);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Edam', 7, 151, 230);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Beef', 10, 83, 231);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kangaroo', 6, 48, 232);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Horseradish', 7, 21, 233);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kale', 9, 64, 234);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pine Nut', 2, 34, 235);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Brown rice vinegar', 2, 67, 236);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sage', 4, 129, 237);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Rice paper', 5, 188, 238);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pear', 4, 178, 239);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Parmesan cheese', 11, 114, 240);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Peppers', 6, 85, 241);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Star Fruit', 2, 191, 242);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Coffee', 11, 132, 243);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corn Syrup', 4, 122, 244);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Watermelon', 11, 200, 245);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Brussels Sprouts', 9, 46, 246);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Octopus', 5, 150, 247);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jelly', 10, 42, 248);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Avocado', 12, 160, 249);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bran', 1, 14, 250);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Jerusalem Artichoke', 11, 113, 251);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Green beans', 12, 178, 252);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corella Pear', 7, 117, 253);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sea Salt', 4, 20, 254);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apple Juice Concentrate', 10, 106, 255);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sesame seed', 3, 77, 256);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cannellini Beans', 5, 118, 257);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Soymilk', 11, 181, 258);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bocconcini', 11, 137, 259);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Poppy Seed', 5, 117, 260);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Green Tea noodles', 6, 65, 261);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Onion', 11, 182, 262);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kombu', 1, 13, 263);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kidney Beans', 7, 27, 264);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Amchur', 6, 48, 265);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Trout', 3, 194, 266);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Corn Tortilla', 6, 14, 267);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Choy Sum', 1, 134, 268);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Quinoa', 2, 71, 269);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('FlourOat', 11, 151, 270);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Grape Seed Oil', 8, 36, 271);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cacao', 2, 96, 272);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Omega Spread', 6, 185, 273);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Flat Mushrooms', 1, 124, 274);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Longan', 2, 52, 275);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sweet Potato', 3, 97, 276);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('RyeBread', 4, 142, 277);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Anchovies', 1, 89, 278);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Canola Oil', 6, 13, 279);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Melon', 4, 188, 280);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Wattleseed', 6, 22, 281);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cabbage', 9, 11, 282);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sesame Oil', 1, 89, 283);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Hot smoked salmon', 1, 171, 284);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Snowpeas', 4, 9, 285);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Chicken', 7, 79, 286);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Vegetable spaghetti', 2, 62, 287);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Sake', 3, 155, 288);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Pasta', 1, 164, 289);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('GemGinger', 11, 159, 290);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Radicchio', 8, 39, 291);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cream', 6, 122, 292);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nectarines', 12, 155, 293);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Crabs', 7, 119, 294);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Lentils', 3, 81, 295);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('CarobCarrot', 12, 166, 296);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Apples', 9, 114, 297);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Annatto seed', 8, 46, 298);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Nasturtium', 5, 69, 299);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Walnut', 7, 197, 300);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Basil Basmati rice', 7, 134, 301);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Parsnip', 10, 90, 302);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Chia seeds', 5, 139, 303);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('SwedeSweet Chilli Sauce', 11, 66, 304);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Baking Powder', 3, 37, 305);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Hokkien Noodles', 3, 12, 306);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cornmeal', 2, 42, 307);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Warehou', 5, 96, 308);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Common Cultivated Mushrooms', 4, 183, 309);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Clams', 11, 192, 310);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Kidneys', 9, 8, 311);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Parsley', 4, 2, 312);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Butter', 10, 14, 313);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Bush Tomato', 12, 80, 314);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cumin', 3, 70, 315);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Gruyere', 7, 110, 316);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Buckwheat Flour', 10, 51, 317);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Fennel', 11, 193, 318);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Beans', 12, 155, 319);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Snowpea sprouts', 11, 85, 320);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Berries', 9, 151, 321);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Camellia Tea Oil', 10, 21, 322);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Brown Flour', 3, 171, 323);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Besan', 12, 161, 324);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Cavalo', 7, 92, 325);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Red Lentils', 3, 17, 326);
INSERT INTO Ingredient (name, food_group_id, calories_per_unit, image_id) VALUES ('Silverbeet', 5, 19, 327);